Repository LikeLion-12th-SKHU/LikeLion-12th-TEAM02-FE, pull requests merged in 2024-09, with the labels that each got.

#28 Design: 상점 화면 UI 수정
  package-lock.json
  package.json
  src/pages/Main.jsx
  src/pages/Object.jsx
Labels: 💄 Style

#30 Design: 설정 화면 UI 수정
  src/pages/settings/Settings.jsx
Labels: 💄 Style

#27 Design: 메인 화면 UI 수정
  package-lock.json
  src/App.js
Labels: 💄 Style

#38 feat: 로그인 전역 상태 관리
  package-lock.json
  package.json
  src/App.js
  src/api/instance.js
  src/api/loginInstance.js
  src/components/ProtectedRoute.js
  src/pages/Main.jsx
  src/pages/auth/GoogleLogin.jsx
  src/pages/auth/KakaoLogin.jsx
  src/pages/auth/Login.jsx
  src/pages/auth/Signup.jsx
  src/pages/settings/Settings.jsx
  src/store/useAuthStore.js
Labels: ✨ Feat

#42 Feat: 404컴포넌트 및 에러 처리
  src/App.js
  src/components/friends/RequestMessage.jsx
  src/pages/Errors/NotFound.jsx
  src/pages/Errors/style.jsx
  src/pages/chat/Chat.jsx
  src/pages/friends/Friends.jsx
Labels: ✨ Feat

#43 Style: Setting페이지 깨지는 현상 수정
  src/pages/settings/Settings.jsx
Labels: 💄 Style

#45 Test: QA 시트 반영 완료
  src/api/friendApi.js
  src/api/instance.js
  src/api/loginInstance.js
  src/components/friends/FriendCard.jsx
  src/components/tracker/style.css
  src/pages/Main.jsx
  src/pages/chat/style.css
  src/pages/friends/RequestList.jsx
  src/pages/tracker/Tracker.jsx
  src/styles/friends.js
  src/styles/tracker.js
Labels: ✨ Feat, ✅ Test

#48 Fix: QA 시트 2차 반영
  src/App.js
  src/api/instance.js
  src/pages/auth/GoogleLogin.jsx
  src/pages/auth/KakaoLogin.jsx
  src/pages/friends/Friends.jsx
  src/pages/settings/InformationSettings.jsx
  src/pages/settings/Settings.jsx
  src/pages/settings/WithdrawalSettings.jsx
  src/store/useAuthStore.js
  src/styles/friends.js
Labels: ⚒️ Fix

#50 Fix: 오브제 쪽 UI 수정
  package.json
  src/pages/Main.jsx
  src/pages/Object.jsx
  src/pages/objects/Flooring.jsx
  src/pages/objects/Furniture.jsx
  src/pages/objects/Gift.jsx
  src/pages/objects/LeftAccessory.jsx
  src/pages/objects/LeftWall.jsx
  src/pages/objects/RightAccessory.jsx
  src/pages/objects/RightWall.jsx
  src/pages/objects/Rug.jsx
  src/pages/objects/SideTable.jsx
  src/pages/objects/Sofa.jsx
  src/pages/objects/Toy.jsx
  src/pages/objects/Wallpaper.jsx
  src/pages/settings/Settings.jsx
  src/pages/shop/Payment.jsx
  src/pages/shop/PaymentResult.jsx
  src/pages/shop/Shop.jsx
Labels: ⚒️ Fix, 💄 Style

#46 📃 docs: readme 추가
  README.md
Labels: 📃 Docs
