Repository LikeLion-12th-SKHU/LikeLion-12th-TEAM02-FE, pull requests merged in 2024-08, with the labels that each got.

#10 Feature/settings
  src/App.js
  src/api/api.js
  src/assets/icons/BackArrow.svg
  src/assets/icons/Check.svg
  src/assets/icons/Feedback.svg
  src/assets/icons/FrontArrow.svg
  src/assets/icons/Logout.svg
  src/assets/icons/Profile.svg
  src/assets/icons/UserInform.svg
  src/assets/icons/Withdrawal.svg
  src/components/KakaoCallback.jsx
  src/components/common/Menubar.jsx
  src/index.js
  src/pages/Main.jsx
  src/pages/auth/Login.jsx
  src/pages/auth/Signup.jsx
  src/pages/friends/Friends.jsx
  src/pages/settings/EditSettings.jsx
  src/pages/settings/InformationSettings.jsx
  src/pages/settings/Settings.jsx
  src/pages/settings/WithdrawalSettings.jsx
  src/styles/Spinner.js
Labels: ✨ Feat

#12 Feat: 친구 목록/추가/삭제 기능 구현 및 스타일링
  src/App.js
  src/api/diaryApi.js
  src/api/friendApi.js
  src/components/friends/FriendCard.jsx
  src/pages/friends/Friends.jsx
  src/pages/friends/RequestList.jsx
  src/pages/tracker/RecommendHospital.jsx
  src/styles/friends.js
Labels: ✨ Feat

#15 Feat: 호야 채팅 기능 구현
  src/assets/icons/HoyaChatProfile.png
  src/pages/chat/Chat.jsx
  src/pages/chat/style.css
Labels: ✨ Feat

#14 Feat: 메인 기능 구현
  src/App.js
  src/assets/icons/BlackHeartObj.svg
  src/assets/icons/BlueCheck.svg
  src/assets/icons/Dialog.svg
  src/assets/icons/ObjCheck.svg
  src/assets/icons/PinkHeartObj.svg
  src/assets/icons/Shop.svg
  src/assets/icons/WhiteBackArrow.svg
  src/assets/icons/X.svg
  src/pages/Main.jsx
  src/pages/Object.jsx
  src/pages/objects/Flooring.jsx
  src/pages/objects/Furniture.jsx
  src/pages/objects/Gift.jsx
  src/pages/objects/LeftAccessory.jsx
  src/pages/objects/LeftWall.jsx
  src/pages/objects/RightAccessory.jsx
  src/pages/objects/RightWall.jsx
  src/pages/objects/Rug.jsx
  src/pages/objects/SideTable.jsx
  src/pages/objects/Sofa.jsx
  src/pages/objects/Toy.jsx
  src/pages/objects/Wallpaper.jsx
  src/pages/settings/InformationSettings.jsx
  src/pages/shop/Shop.jsx
Labels: ✨ Feat, 💄 Style

#18 Feat: AI 일기 요약 구현
  src/api/diaryApi.js
  src/components/tracker/DiaryDetailForm.jsx
  src/pages/tracker/DiaryDetail.jsx
  src/pages/tracker/EditDiary.jsx
  src/pages/tracker/RecommendHospital.jsx
  src/pages/tracker/Tracker.jsx
  src/styles/tracker.js
Labels: ✨ Feat

#19 Style: 공통 컴포넌트 추가
  public/index.html
  src/App.js
  src/api/friendApi.js
  src/components/common/Header.jsx
  src/components/common/Loading.jsx
  src/components/common/Menubar.jsx
  src/components/common/MobileWarning.jsx
  src/components/common/style.css
  src/components/friends/RequestMessage.jsx
  src/components/tracker/DiaryCalendar.jsx
  src/components/tracker/DiaryForm.jsx
  src/components/tracker/style.css
  src/pages/chat/Chat.jsx
  src/pages/friends/Friends.jsx
  src/pages/friends/RequestList.jsx
  src/pages/tracker/CreateDiary.jsx
  src/pages/tracker/DiaryDetail.jsx
  src/pages/tracker/EditDiary.jsx
  src/pages/tracker/RecommendHospital.jsx
  src/pages/tracker/Tracker.jsx
  src/styles/tracker.js
Labels: 💄 Style

#22 Design: 모바일에서 일부 깨지는 현상 수정
  src/api/diaryApi.js
  src/components/tracker/style.css
  src/styles/GlobalStyle.js
  src/styles/friends.js
Labels: 💄 Style
